events {}

http
{
	map $http_upgrade $connection_upgrade {
		default upgrade;
		''      close;
	}

	include       /etc/nginx/mime.types;
	default_type  application/octet-stream;

	server
	{
		listen 443 ssl default_server;
		server_name sberete.42.fr;

		ssl_certificate     /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;
		ssl_protocols       TLSv1.2 TLSv1.3;

		root /var/www/html;
		index index.php index.html;

		location /
		{
			try_files $uri $uri/ /index.php?$args;
		}

		location /adminer/ 
		{
			proxy_pass http://adminer:8080/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		}
		
		location /fatherfinder/
		{
			proxy_pass http://static-site/;
			proxy_set_header Host $host;
		}

		location ~ \.php$
		{
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}

	server
	{
		listen 443 ssl;
		server_name kuma.sberete.42.fr;

		ssl_certificate     /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;
		ssl_protocols       TLSv1.2 TLSv1.3;

		location /
		{
			proxy_pass http://uptime-kuma:3001/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;

			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;
			proxy_read_timeout 86400;
			proxy_buffering off;
		}
	}
}